echo ------------------
echo clean
echo ------------------
cat clean
echo ------------------
echo run_proc.sh
echo ------------------
cat run_proc.sh
echo ------------------
echo stats.py
echo ------------------
cat stats.py
echo ------------------
echo Analysis and visualization
echo ------------------
echo agcensus_data_scenarios.py
echo ------------------
cat agcensus_data_scenarios.py
echo ------------------
echo county_dist.py
echo ------------------
cat county_dist.py
echo ------------------
echo state_dist.py
echo ------------------ 
cat state_dist.py
echo ------------------
echo transfer.sh
echo ------------------
cat transfer.sh
echo ------------------
echo Verification
echo ------------------
echo verify.sh
echo ------------------
cat verify.sh
echo ------------------